-- ========================================
-- SEED DATA - Real test data
-- ========================================
-- Insert default user
INSERT INTO users (
    name,
    email,
    company,
    role,
    linkedin_connected,
    settings,
    created_at,
    updated_at
  )
VALUES (
    'Dorra Boucharbia',
    'dorraboucharbia@gmail.com',
    'LinkedIn Agent',
    'CEO & Founder',
    true,
    '{"notifications": true, "auto_connect": false, "daily_limit": 50}',
    NOW(),
    NOW()
  ) ON CONFLICT (email) DO NOTHING;
-- Insert realistic prospects
INSERT INTO prospects (
    linkedin_url,
    name,
    role,
    company,
    industry,
    location,
    company_size,
    email,
    score,
    status,
    notes,
    created_at,
    updated_at
  )
VALUES (
    'https://linkedin.com/in/jean-martin-tech',
    'Jean Martin',
    'CTO',
    'TechCorp France',
    'Technology',
    'Paris',
    '51-200',
    'jean.martin@techcorp.fr',
    85,
    'new',
    'Cible prioritaire - CTO de scale-up tech',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/sarah-dubois-saas',
    'Sarah Dubois',
    'Sales Director',
    'SaaS Solutions',
    'SaaS',
    'Lyon',
    '11-50',
    'sarah.dubois@saassol.fr',
    78,
    'contacted',
    'Interested in our solutions',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/pierre-leroy-finance',
    'Pierre Leroy',
    'VP Engineering',
    'FinanceHub',
    'Fintech',
    'Paris',
    '201-500',
    'p.leroy@financehub.eu',
    82,
    'new',
    'VP Engineering - Bonne cible pour prospection',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/marie-claire-ai',
    'Marie Claire',
    'Head of AI',
    'AI Innovations',
    'Artificial Intelligence',
    'Bordeaux',
    '11-50',
    'marie@ai-innovations.tech',
    90,
    'responded',
    'Very interested - follow up quickly',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/thomas-petit-startup',
    'Thomas Petit',
    'CEO',
    'StartupBoost',
    'Startups',
    'Marseille',
    '1-10',
    'thomas@startupboost.io',
    75,
    'new',
    'CEO early stage - opportunity',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/alexandre-moreau-dev',
    'Alexandre Moreau',
    'Lead Developer',
    'DevStudio',
    'Software',
    'Nantes',
    '11-50',
    'alex@devstudio.fr',
    68,
    'new',
    'Lead dev - possible decision maker',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/celine-robert-rh',
    'Celine Robert',
    'HR Director',
    'TalentPro',
    'HR Tech',
    'Toulouse',
    '51-200',
    'celine@talentpro.com',
    72,
    'contacted',
    'HR Director - interested in automation',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/nicolas-vincent-cloud',
    'Nicolas Vincent',
    'Cloud Architect',
    'CloudFirst',
    'Cloud Computing',
    'Paris',
    '201-500',
    'n.vincent@cloudfirst.fr',
    80,
    'new',
    'Cloud architect - technical buyer',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/julie-bernard-marketing',
    'Julie Bernard',
    'CMO',
    'GrowthMarketing',
    'Marketing',
    'Lille',
    '11-50',
    'julie@growthmarketing.fr',
    76,
    'responded',
    'CMO - looking for qualified leads',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/david-roussel-ecommerce',
    'David Roussel',
    'E-commerce Manager',
    'ShopOnline',
    'E-commerce',
    'Strasbourg',
    '51-200',
    'david@shoponline.fr',
    70,
    'new',
    'E-commerce - cible pour prospection B2B',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/emma-durand-product',
    'Emma Durand',
    'Product Manager',
    'ProductLab',
    'Product',
    'Rennes',
    '11-50',
    'emma@productlab.io',
    74,
    'contacted',
    'PM - wants to improve pipeline',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/philippe-garcia-consultant',
    'Philippe Garcia',
    'Consultant Senior',
    'BigConsulting',
    'Consulting',
    'Paris',
    '5001-10000',
    'philippe.garcia@bigconsulting.com',
    65,
    'new',
    'Consultant - possible referrer',
    NOW(),
    NOW()
  ) ON CONFLICT (linkedin_url) DO NOTHING;
-- Insert campaigns
INSERT INTO campaigns (
    name,
    description,
    industry,
    location,
    company_size,
    target_role,
    template_invitation,
    template_followup,
    status,
    contacted,
    replied,
    clicked,
    converted,
    created_at,
    updated_at
  )
VALUES (
    'Tech Paris Campaign',
    'Prospecting CTO and VP Engineering in tech in Paris',
    'Technology',
    'Paris',
    '51-200',
    'CTO,VP Engineering',
    'Hello {{name}},\n\nI noticed your technical expertise at {{company}}. I am working on a LinkedIn automation solution that helps tech leaders scale their B2B prospecting.\n\nWould you be open to a 15-minute call to see if this could interest you?\n\nBest,\nDorra',
    'Hello {{name}},\n\nI am following up on my previous message. I would really appreciate your feedback on our solution.\n\nBest,\nDorra',
    'active',
    45,
    12,
    8,
    3,
    NOW() - INTERVAL '30 days',
    NOW()
  ),
  (
    'SaaS Lyon & Bordeaux',
    'Targeting Sales Directors and Head of Sales in SaaS',
    'SaaS',
    'Lyon,Bordeaux',
    '11-50',
    'Sales Director,Head of Sales',
    'Hello {{name}},\n\n{{company}} is growing nicely! I offer a solution that helps sales teams generate 3x more appointments via LinkedIn.\n\nWould you like to talk about it?',
    '{{name}}, just a quick follow-up on my message. Have you had a chance to think about it?',
    'active',
    32,
    8,
    5,
    2,
    NOW() - INTERVAL '20 days',
    NOW()
  ),
  (
    'Fintech Scale-up',
    'Fintech prospecting in scale phase',
    'Fintech',
    'Paris',
    '51-200',
    'CEO,Co-Founder',
    '{{name}},\n\nFintech scale-ups like {{company}} need a predictable sales pipeline. My LinkedIn AI agent helps book 15+ qualified appointments per month.\n\nInterested in a demo?',
    'I understand you are busy {{name}}, but I promise it is worth taking a look :)',
    'paused',
    28,
    4,
    2,
    1,
    NOW() - INTERVAL '45 days',
    NOW()
  ),
  (
    'Early Stage Startups',
    'Ciblage fondateurs de startups early stage',
    'Startups',
    'France',
    '1-10',
    'CEO,Founder',
    'Hi {{name}},\n\nI know early stage is intense. I created a tool that does LinkedIn prospecting for you so you can focus on the product.\n\nWant to try it?',
    'Still up for automating your prospecting {{name}}? I can show you how it works in 5 min.',
    'draft',
    0,
    0,
    0,
    0,
    NOW() - INTERVAL '5 days',
    NOW()
  ) ON CONFLICT DO NOTHING;
-- Insert messages
INSERT INTO messages (
    prospect_id,
    campaign_id,
    recipient_name,
    recipient_role,
    recipient_company,
    message_text,
    message_type,
    status,
    created_at
  )
VALUES (
    2,
    1,
    'Sarah Dubois',
    'Sales Director',
    'SaaS Solutions',
    'Hello Sarah,\n\nI noticed your sales expertise at SaaS Solutions. I am working on a LinkedIn automation solution that helps leaders scale their B2B prospecting.\n\nWould you be open to a 15-minute call?',
    'connection',
    'replied',
    NOW() - INTERVAL '3 days'
  ),
  (
    3,
    1,
    'Pierre Leroy',
    'VP Engineering',
    'FinanceHub',
    'Hello Pierre,\n\nFinanceHub is growing nicely! I offer a solution that helps teams generate more leads via LinkedIn.\n\nWould you like to talk about it?',
    'connection',
    'sent',
    NOW() - INTERVAL '1 day'
  ),
  (
    4,
    2,
    'Marie Claire',
    'Head of AI',
    'AI Innovations',
    'Marie, I love what you are doing at AI Innovations! I would like to show you how my AI agent can help you find more clients.',
    'connection',
    'replied',
    NOW() - INTERVAL '5 days'
  ),
  (
    7,
    1,
    'Celine Robert',
    'HR Director',
    'TalentPro',
    'Hello Celine,\n\nI saw that TalentPro is actively hiring. My tool can also help you source candidates on LinkedIn!',
    'followup',
    'read',
    NOW() - INTERVAL '12 hours'
  ),
  (
    9,
    2,
    'Julie Bernard',
    'CMO',
    'GrowthMarketing',
    'Julie, your growth strategy at GrowthMarketing is impressive! I think my AI agent could help you generate even more leads.',
    'connection',
    'responded',
    NOW() - INTERVAL '2 days'
  ),
  (
    11,
    2,
    'Emma Durand',
    'Product Manager',
    'ProductLab',
    'Hi Emma, I am following up on my message. Still interested in seeing how to automate your prospecting?',
    'followup',
    'sent',
    NOW() - INTERVAL '4 hours'
  ) ON CONFLICT DO NOTHING;
-- Insert message templates
INSERT INTO templates (
    name,
    tag,
    text,
    usage_count,
    conversion_rate,
    created_at,
    updated_at
  )
VALUES (
    'First contact',
    'Invitation',
    'Hello {{first_name}}, I noticed your profile and your work at {{company}} really impressed me. I am developing {{short_pitch}}. Would you be available for a quick chat?',
    142,
    24,
    NOW(),
    NOW()
  ),
  (
    'Follow-up message',
    'Follow-up',
    'Hello {{first_name}}, I wanted to follow up on my invitation. I am working on {{solution}} and I think it could really help you {{benefit}}. 15 minutes this week?',
    89,
    18,
    NOW(),
    NOW()
  ),
  (
    'Link sharing',
    'Nurturing',
    'Hello {{first_name}}, following our conversation, I am sharing this link that explains how similar {{company}} achieved {{result}}. Curious to hear your thoughts!',
    56,
    31,
    NOW(),
    NOW()
  ),
  (
    'Final follow-up',
    'Relance',
    'Hello {{first_name}}, I do not want to bother you further. Just leaving this link in case: {{link}}. Feel free to reach out if timing changes!',
    34,
    12,
    NOW(),
    NOW()
  ) ON CONFLICT DO NOTHING;