-- ========================================
-- SEED DATA - Données de test réelles
-- ========================================
-- Insérer un utilisateur par défaut
INSERT INTO users (
    name,
    email,
    company,
    role,
    linkedin_connected,
    settings,
    created_at,
    updated_at
  )
VALUES (
    'Dorra Boucharbia',
    'dorraboucharbia@gmail.com',
    'LinkedIn Agent',
    'CEO & Founder',
    true,
    '{"notifications": true, "auto_connect": false, "daily_limit": 50}',
    NOW(),
    NOW()
  ) ON CONFLICT (email) DO NOTHING;
-- Insérer des prospects réalistes
INSERT INTO prospects (
    linkedin_url,
    name,
    role,
    company,
    industry,
    location,
    company_size,
    email,
    score,
    status,
    notes,
    created_at,
    updated_at
  )
VALUES (
    'https://linkedin.com/in/jean-martin-tech',
    'Jean Martin',
    'CTO',
    'TechCorp France',
    'Technology',
    'Paris',
    '51-200',
    'jean.martin@techcorp.fr',
    85,
    'new',
    'Cible prioritaire - CTO de scale-up tech',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/sarah-dubois-saas',
    'Sarah Dubois',
    'Sales Director',
    'SaaS Solutions',
    'SaaS',
    'Lyon',
    '11-50',
    'sarah.dubois@saassol.fr',
    78,
    'contacted',
    'Intéressée par nos solutions',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/pierre-leroy-finance',
    'Pierre Leroy',
    'VP Engineering',
    'FinanceHub',
    'Fintech',
    'Paris',
    '201-500',
    'p.leroy@financehub.eu',
    82,
    'new',
    'VP Engineering - Bonne cible pour prospection',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/marie-claire-ai',
    'Marie Claire',
    'Head of AI',
    'AI Innovations',
    'Artificial Intelligence',
    'Bordeaux',
    '11-50',
    'marie@ai-innovations.tech',
    90,
    'responded',
    'Très intéressée - à relancer rapidement',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/thomas-petit-startup',
    'Thomas Petit',
    'CEO',
    'StartupBoost',
    'Startups',
    'Marseille',
    '1-10',
    'thomas@startupboost.io',
    75,
    'new',
    'CEO early stage - opportunité',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/alexandre-moreau-dev',
    'Alexandre Moreau',
    'Lead Developer',
    'DevStudio',
    'Software',
    'Nantes',
    '11-50',
    'alex@devstudio.fr',
    68,
    'new',
    'Lead dev - possible decision maker',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/celine-robert-rh',
    'Céline Robert',
    'HR Director',
    'TalentPro',
    'HR Tech',
    'Toulouse',
    '51-200',
    'celine@talentpro.com',
    72,
    'contacted',
    'RH Director - intéressée par l''automatisation',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/nicolas-vincent-cloud',
    'Nicolas Vincent',
    'Cloud Architect',
    'CloudFirst',
    'Cloud Computing',
    'Paris',
    '201-500',
    'n.vincent@cloudfirst.fr',
    80,
    'new',
    'Cloud architect - technical buyer',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/julie-bernard-marketing',
    'Julie Bernard',
    'CMO',
    'GrowthMarketing',
    'Marketing',
    'Lille',
    '11-50',
    'julie@growthmarketing.fr',
    76,
    'responded',
    'CMO - cherche des leads qualifiés',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/david-roussel-ecommerce',
    'David Roussel',
    'E-commerce Manager',
    'ShopOnline',
    'E-commerce',
    'Strasbourg',
    '51-200',
    'david@shoponline.fr',
    70,
    'new',
    'E-commerce - cible pour prospection B2B',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/emma-durand-product',
    'Emma Durand',
    'Product Manager',
    'ProductLab',
    'Product',
    'Rennes',
    '11-50',
    'emma@productlab.io',
    74,
    'contacted',
    'PM - veut améliorer son pipeline',
    NOW(),
    NOW()
  ),
  (
    'https://linkedin.com/in/philippe-garcia-consultant',
    'Philippe Garcia',
    'Consultant Senior',
    'BigConsulting',
    'Consulting',
    'Paris',
    '5001-10000',
    'philippe.garcia@bigconsulting.com',
    65,
    'new',
    'Consultant - possible referrer',
    NOW(),
    NOW()
  ) ON CONFLICT (linkedin_url) DO NOTHING;
-- Insérer des campagnes
INSERT INTO campaigns (
    name,
    description,
    industry,
    location,
    company_size,
    target_role,
    template_invitation,
    template_followup,
    status,
    contacted,
    replied,
    clicked,
    converted,
    created_at,
    updated_at
  )
VALUES (
    'Campagne Tech Paris',
    'Prospection CTO et VP Engineering dans la tech à Paris',
    'Technology',
    'Paris',
    '51-200',
    'CTO,VP Engineering',
    'Bonjour {{name}},\n\nJ''ai remarqué votre expertise technique chez {{company}}. Je travaille sur une solution d''automatisation LinkedIn qui aide les dirigeants tech à scaler leur prospection B2B.\n\nSeriez-vous ouvert à un échange de 15 minutes pour voir si cela pourrait vous intéresser ?\n\nBonne journée,\nDorra',
    'Bonjour {{name}},\n\nJe me permets de relancer mon message précédent. J''aimerais vraiment avoir votre retour sur notre solution.\n\nÀ bientôt,\nDorra',
    'active',
    45,
    12,
    8,
    3,
    NOW() - INTERVAL '30 days',
    NOW()
  ),
  (
    'SaaS Lyon & Bordeaux',
    'Ciblage Sales Directors et Head of Sales dans le SaaS',
    'SaaS',
    'Lyon,Bordeaux',
    '11-50',
    'Sales Director,Head of Sales',
    'Hello {{name}},\n\n{{company}} connaît une belle croissance ! Je propose une solution qui aide les équipes commerciales à générer 3x plus de rendez-vous via LinkedIn.\n\nÇa vous dirait d''en parler ?',
    '{{name}}, juste un petit follow-up sur mon message. Vous avez eu le temps d''y réfléchir ?',
    'active',
    32,
    8,
    5,
    2,
    NOW() - INTERVAL '20 days',
    NOW()
  ),
  (
    'Fintech Scale-up',
    'Prospection fintech en phase de scale',
    'Fintech',
    'Paris',
    '51-200',
    'CEO,Co-Founder',
    '{{name}},\n\nLes scale-ups fintech comme {{company}} ont besoin d''un pipeline commercial prévisible. Mon agent IA LinkedIn aide à booker 15+ RDV qualifiés par mois.\n\nIntéressé pour voir une démo ?',
    'Je comprends que vous êtes débordé {{name}}, mais promis, ça vaut le coup de jeter un œil :)',
    'paused',
    28,
    4,
    2,
    1,
    NOW() - INTERVAL '45 days',
    NOW()
  ),
  (
    'Early Stage Startups',
    'Ciblage fondateurs de startups early stage',
    'Startups',
    'France',
    '1-10',
    'CEO,Founder',
    'Salut {{name}},\n\nJe sais que le early stage c''est intense. J''ai créé un outil qui fait le prospecting LinkedIn à votre place pour que vous vous concentreriez sur le produit.\n\nTu veux tester ?',
    'Toujours partant pour automatiser ta prospection {{name}} ? Je peux te montrer comment ça marche en 5 min.',
    'draft',
    0,
    0,
    0,
    0,
    NOW() - INTERVAL '5 days',
    NOW()
  ) ON CONFLICT DO NOTHING;
-- Insérer des messages
INSERT INTO messages (
    prospect_id,
    campaign_id,
    recipient_name,
    recipient_role,
    recipient_company,
    message_text,
    message_type,
    status,
    created_at
  )
VALUES (
    2,
    1,
    'Sarah Dubois',
    'Sales Director',
    'SaaS Solutions',
    'Bonjour Sarah,\n\nJ''ai remarqué votre expertise commerciale chez SaaS Solutions. Je travaille sur une solution d''automatisation LinkedIn qui aide les dirigeants à scaler leur prospection B2B.\n\nSeriez-vous ouvert à un échange de 15 minutes ?',
    'connection',
    'replied',
    NOW() - INTERVAL '3 days'
  ),
  (
    3,
    1,
    'Pierre Leroy',
    'VP Engineering',
    'FinanceHub',
    'Hello Pierre,\n\nFinanceHub connaît une belle croissance ! Je propose une solution qui aide les équipes à générer plus de leads via LinkedIn.\n\nÇa vous dirait d''en parler ?',
    'connection',
    'sent',
    NOW() - INTERVAL '1 day'
  ),
  (
    4,
    2,
    'Marie Claire',
    'Head of AI',
    'AI Innovations',
    'Marie, j''adore ce que vous faites chez AI Innovations ! J''aimerais vous montrer comment mon agent IA peut vous aider à trouver plus de clients.',
    'connection',
    'replied',
    NOW() - INTERVAL '5 days'
  ),
  (
    7,
    1,
    'Céline Robert',
    'HR Director',
    'TalentPro',
    'Bonjour Céline,\n\nJ''ai vu que TalentPro recrute activement. Mon outil peut aussi vous aider à sourcer des candidats sur LinkedIn !',
    'followup',
    'read',
    NOW() - INTERVAL '12 hours'
  ),
  (
    9,
    2,
    'Julie Bernard',
    'CMO',
    'GrowthMarketing',
    'Julie, votre stratégie growth chez GrowthMarketing est impressionnante ! Je pense que mon agent IA pourrait vous aider à générer encore plus de leads.',
    'connection',
    'responded',
    NOW() - INTERVAL '2 days'
  ),
  (
    11,
    2,
    'Emma Durand',
    'Product Manager',
    'ProductLab',
    'Salut Emma, je me permets de relancer mon message. Toujours intéressée pour voir comment automatiser votre prospection ?',
    'followup',
    'sent',
    NOW() - INTERVAL '4 hours'
  ) ON CONFLICT DO NOTHING;
-- Insérer des templates de messages
INSERT INTO templates (
    name,
    tag,
    text,
    usage_count,
    conversion_rate,
    created_at,
    updated_at
  )
VALUES (
    'Premier contact',
    'Invitation',
    'Bonjour {{prénom}}, j''ai remarqué votre profil et votre travail chez {{entreprise}} m''a vraiment impressionné. Je développe {{pitch_court}}. Seriez-vous disponible pour un échange rapide ?',
    142,
    24,
    NOW(),
    NOW()
  ),
  (
    'Message de suivi',
    'Follow-up',
    'Bonjour {{prénom}}, je voulais faire suite à mon invitation. Je travaille sur {{solution}} et je pense que ça pourrait vraiment vous aider à {{bénéfice}}. 15 minutes cette semaine ?',
    89,
    18,
    NOW(),
    NOW()
  ),
  (
    'Partage de lien',
    'Nurturing',
    'Bonjour {{prénom}}, suite à notre échange, je vous partage ce lien qui explique comment {{entreprise}} similaires ont obtenu {{résultat}}. Curieux d''avoir votre avis !',
    56,
    31,
    NOW(),
    NOW()
  ),
  (
    'Relance finale',
    'Relance',
    'Bonjour {{prénom}}, je ne voudrais pas vous déranger davantage. Juste pour vous laisser ce lien au cas où : {{lien}}. N''hésitez pas si le timing change !',
    34,
    12,
    NOW(),
    NOW()
  ) ON CONFLICT DO NOTHING;