import { NextRequest, NextResponse } from "next/server";
import { pool } from "@/lib/db";

// GET /api/bi/templates?range=30
// Module 2: AI Message Pattern Performance Lab
//  Analyzes messages ACTUALLY generated by the AI agent (messages table),
//  grouped by normalized PATTERN ({name}/{company}/{role} masked).
//  - Scatter usage × conversion by generated pattern
//  - Top / Flop patterns generated by the agent
//  - Winning N-grams (keywords of high-conversion patterns)
//  - Heatmap day × send hour (reply rate)
//  - Message length vs reply rate

// Normalizes a message by masking personalized variables
// to group structurally identical messages generated by the agent.
function normalizePattern(
  text: string,
  name?: string | null,
  company?: string | null,
  role?: string | null
): string {
  let p = text || "";
  const mask = (val: string | null | undefined, token: string) => {
    if (!val) return;
    const trimmed = val.trim();
    if (trimmed.length < 2) return;
    // Mask full name AND each word (first/last) separately
    const parts = [trimmed, ...trimmed.split(/\s+/)].filter(w => w.length >= 2);
    for (const part of parts) {
      const esc = part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      p = p.replace(new RegExp(esc, "gi"), token);
    }
  };
  mask(name, "{name}");
  mask(company, "{company}");
  mask(role, "{role}");
  // Collapse spaces / line breaks for robust grouping
  return p.replace(/\s+/g, " ").trim();
}

// Generates a readable name for a pattern from its start
function patternName(normalized: string, index: number): string {
  const preview = normalized.replace(/\{(name|company|role)\}/g, "…").slice(0, 40).trim();
  return preview ? `Pattern: "${preview}…"` : `Pattern #${index + 1}`;
}
const STOPWORDS = new Set([
  "the","a","an","of","and","or","to","in","on","at","for","with","is","are","be","been","being","you","i","we","they","he","she","it","this","that","these","those","my","your","our","their","his","her","its","hello","hi","dear","best","kind","regards","thanks","thank","please","could","would","should","will","shall","may","might","can","do","does","did","done","have","has","had","get","got","gotten","make","made","say","said","go","went","gone","come","came","know","knew","known","take","took","taken","see","saw","seen","want","wanted","use","used","find","found","give","gave","given","tell","told","work","worked","call","called","try","tried","need","needed","feel","felt","become","became","become","leave","left","put","keep","kept","let","begin","began","begun","seem","seemed","help","helped","show","showed","shown","hear","heard","play","played","run","ran","run","move","moved","live","lived","believe","believed","bring","brought","happen","happened","write","wrote","written","provide","provided","sit","sat","stand","stood","lose","lost","pay","paid","meet","met","include","included","continue","continued","set","learn","learned","learnt","change","changed","lead","led","understand","understood","watch","watched","follow","followed","stop","stopped","create","created","speak","spoke","spoken","read","allow","allowed","add","added","spend","spent","grow","grew","grown","open","opened","walk","walked","win","won","offer","offered","remember","remembered","love","loved","consider","considered","appear","appeared","buy","bought","wait","waited","serve","served","die","died","send","sent","expect","expected","build","built","stay","stayed","fall","fell","fallen","cut","reach","reached","kill","killed","remain","remained","suggest","suggested","raise","raised","pass","passed","sell","sold","require","required","report","reported","decide","decided","pull","pulled",
]);

function tokens(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z\s]/gi, " ")
    .split(/\s+/)
    .filter(w => w.length >= 4 && !STOPWORDS.has(w));
}

export async function GET(req: NextRequest) {
  try {
    const range = parseInt(req.nextUrl.searchParams.get("range") || "30");

    // Messages actually generated by the AI agent (with personalization info for normalization)
    const msgSql = `
      SELECT
        message_text,
        recipient_name,
        recipient_company,
        recipient_role,
        message_type,
        status
      FROM messages
      WHERE created_at > NOW() - INTERVAL '1 day' * $1
        AND message_text IS NOT NULL
    `;

    // Heatmap day × hour (based on messages.created_at, replied marking)
    const heatmapSql = `
      SELECT
        EXTRACT(DOW FROM created_at)::int AS dow,
        EXTRACT(HOUR FROM created_at)::int AS hour,
        COUNT(*) AS sent,
        COUNT(*) FILTER (WHERE status = 'replied') AS replied
      FROM messages
      WHERE created_at > NOW() - INTERVAL '1 day' * $1
      GROUP BY dow, hour
      ORDER BY dow, hour
    `;

    // Message length vs reply rate (by buckets)
    const lengthSql = `
      WITH bucketed AS (
        SELECT
          CASE
            WHEN LENGTH(message_text) < 100 THEN '0-100'
            WHEN LENGTH(message_text) < 200 THEN '100-200'
            WHEN LENGTH(message_text) < 300 THEN '200-300'
            WHEN LENGTH(message_text) < 500 THEN '300-500'
            WHEN LENGTH(message_text) < 800 THEN '500-800'
            ELSE '800+'
          END AS bucket,
          status
        FROM messages
        WHERE created_at > NOW() - INTERVAL '1 day' * $1
      )
      SELECT
        bucket,
        COUNT(*) AS total,
        COUNT(*) FILTER (WHERE status = 'replied') AS replied
      FROM bucketed
      GROUP BY 1
      ORDER BY 1
    `;

    const [msgR, hmR, lenR] = await Promise.all([
      pool.query(msgSql, [range]),
      pool.query(heatmapSql, [range]),
      pool.query(lengthSql, [range]),
    ]);

    // Group messages generated by the agent into normalized PATTERNS
    type Group = { pattern: string; tag: string; sent: number; replied: number; totalLen: number };
    const groups = new Map<string, Group>();
    for (const m of msgR.rows) {
      const normalized = normalizePattern(
        m.message_text,
        m.recipient_name,
        m.recipient_company,
        m.recipient_role
      );
      if (!normalized || normalized.length < 5) continue;
      const key = normalized.toLowerCase();
      let g = groups.get(key);
      if (!g) {
        g = { pattern: normalized, tag: m.message_type || "message", sent: 0, replied: 0, totalLen: 0 };
        groups.set(key, g);
      }
      g.sent += 1;
      g.totalLen += (m.message_text || "").length;
      if (m.status === "replied") g.replied += 1;
    }

    // Build the list of patterns (= "templates" generated by the agent)
    const templates = Array.from(groups.values())
      .map((g, i) => ({
        id: i + 1,
        name: patternName(g.pattern, i),
        tag: g.tag,
        pattern: g.pattern,
        usage: g.sent,
        conversion: g.sent > 0 ? Math.round((g.replied / g.sent) * 100) : 0,
        length: g.sent > 0 ? Math.round(g.totalLen / g.sent) : 0,
      }))
      .sort((a, b) => b.conversion - a.conversion || b.usage - a.usage)
      .slice(0, 50);

    // N-grams (words) — top conversion patterns (>= median)
    const sortedConv = [...templates].sort((a, b) => b.conversion - a.conversion);
    const topHalf = sortedConv.slice(0, Math.max(1, Math.floor(sortedConv.length / 2)));
    const topIds = new Set(topHalf.map(t => t.id));
    const wordScores: Record<string, { good: number; bad: number }> = {};
    for (const t of templates) {
      const isGood = topIds.has(t.id);
      const ws = tokens(t.pattern || "");
      for (const w of ws) {
        if (!wordScores[w]) wordScores[w] = { good: 0, bad: 0 };
        if (isGood) wordScores[w].good += 1;
        else wordScores[w].bad += 1;
      }
    }
    const winningWords = Object.entries(wordScores)
      .map(([w, s]) => ({ word: w, score: s.good - s.bad, good: s.good, bad: s.bad }))
      .filter(x => x.good >= 1)
      .sort((a, b) => b.score - a.score)
      .slice(0, 12);

    // Normalized heatmap (reply rate %)
    const heatmap = hmR.rows.map(r => {
      const sent = parseInt(r.sent) || 0;
      const replied = parseInt(r.replied) || 0;
      return {
        dow: parseInt(r.dow),
        hour: parseInt(r.hour),
        sent,
        replied,
        rate: sent > 0 ? Math.round((replied / sent) * 100) : 0,
      };
    });

    const lengthBuckets = lenR.rows.map(r => {
      const total = parseInt(r.total) || 0;
      const replied = parseInt(r.replied) || 0;
      return {
        bucket: r.bucket,
        total,
        replied,
        rate: total > 0 ? Math.round((replied / total) * 100) : 0,
      };
    });

    return NextResponse.json({
      success: true,
      templates,
      winningWords,
      heatmap,
      lengthBuckets,
      range,
    });
  } catch (error) {
    console.error("GET /api/bi/templates error:", error);
    return NextResponse.json({ success: false, error: String(error) }, { status: 500 });
  }
}
